image: node:14.17.5

pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - node -v
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:0.2.1
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT